aragon/aragon-court

contracts/lib/HexSumTree.sol
contracts/test/HexSumTreePublic.sol
package.json
test/hex-tree-gas.js
test/hex-tree.js

And add more gas tests for SumTree Sortition lib.
Fixes #10.

Split gas tests

---

contracts/Court.sol
contracts/test/CourtMock.sol
test/court-batches.js
test/court-disputes.js

Court: remove dismiss dispute

---

contracts/Court.sol
contracts/test/CourtMock.sol
test/court-batches.js
test/court-disputes.js
test/court-final-appeal-non-exact.js
test/court-final-appeal.js

Batch settle round slashing

---

contracts/Court.sol
contracts/test/CourtMock.sol
test/court-batches.js
test/court-disputes.js

Drafting will have to wait for a later term where randomness seed is
available.
Closes #15.

Court: prevents drafting without randomness seed

---

contracts/Court.sol
contracts/CourtSubscriptions.sol
contracts/HexSumTreeWrapper.sol
contracts/standards/subscription/ISubscriptions.sol
contracts/standards/subscription/ISubscriptionsOwner.sol
contracts/standards/sumtree/ISumTree.sol
contracts/test/CourtMock.sol
contracts/test/SubscriptionsMock.sol
contracts/test/SubscriptionsOwnerMock.sol
package.json
test/court-batches.js
test/court-disputes.js
test/court-final-appeal-non-exact.js
test/court-final-appeal.js
test/court-lifecycle.js
test/court-staking.js
test/subscription-fees.js

Closes #51 
Replaces #57 (Updated rebasing onto last changes, keeping the old one closed for discussion reference).

Subscription fees

---

contracts/Court.sol
contracts/JurorsRegistry.sol
contracts/standards/erc900/IJurorsRegistry.sol

Small enhancement to encapsulate a bit more the idea of hiding a tree behind the juror registry.

Registry: Simplify total active balance getter

---

.travis.yml

Chore: Upgrade CI node to version 10

---

contracts/court/Court.sol
contracts/lib/Checkpointing.sol
contracts/lib/HexSumTree.sol
contracts/registry/JurorsRegistry.sol
contracts/subscriptions/CourtSubscriptions.sol
contracts/test/standards/ERC20Mock.sol
contracts/voting/CRVoting.sol

**MERGE AFTER #134**
Fixes #79

Subscriptions: Write inline documentation

---

contracts/voting/CRVoting.sol
contracts/voting/ICRVoting.sol
test/voting/crvoting-commit.js
test/voting/crvoting-integration.js
test/voting/crvoting-leak.js

Voting: Remove winning outcome tally getter

---

contracts/subscriptions/CourtSubscriptions.sol

**MERGE AFTER https://github.com/aragon/aragon-court/pull/135**

Subscriptions: Organize functions according linter rules

---

test/court/court-confirm-appeal.js

Court: Test final rounds jurors number immutability

---

contracts/subscriptions/CourtSubscriptions.sol
test/subscriptions/subscriptions-initialization.js
test/subscriptions/subscriptions-jurors.js
test/subscriptions/subscriptions-payments.js
test/subscriptions/subscriptions-setters.js

Subscriptions: Polish contract

---

contracts/court/CourtAccounting.sol
contracts/registry/JurorsRegistry.sol
contracts/subscriptions/CourtSubscriptions.sol
test/court/court-accounting.js
test/subscriptions/subscriptions-initialization.js

Contracts: Use Initializable contract

---

.travis.yml
contracts/court/Court.sol
contracts/test/court/CourtMock.sol
contracts/test/lib/TimeHelpersMock.sol
test/court/court-disputes.js
test/court/court-draft.js
test/court/court-settle-appeal.js
test/court/court-settle-round.js
test/court/court-settle.js
truffle-config.js

Fixes #101 
I recommend reviewing per commit since I had to split the settles tests into two separate files to avoid a timeout on the CI

Court: Fix appeal fees reimbursements

---

package.json

Add gas reporter

---

contracts/court/Court.sol
contracts/lib/Checkpointing.sol
contracts/lib/HexSumTree.sol
contracts/lib/JurorsTreeSortition.sol
contracts/lib/PctHelpers.sol
contracts/registry/JurorsRegistry.sol
contracts/subscriptions/CourtSubscriptions.sol
contracts/voting/CRVoting.sol
test/helpers/court.js
test/lib/hex-sum-tree.js

Also added comments to every place where it's not needed explaining
the reason.
Fixes #22.
TODO:

Contracts: Add SafeMath

---

contracts/court/CourtAccounting.sol

**MERGE AFTER https://github.com/aragon/aragon-court/pull/151**

Accounting: Write inline doc

---

test/court/court-gas.js
test/lib/hex-sum-tree-gas.js
truffle-config.js

Gas costs were improved a bit :)

Contracts: Enable optimizer with 10,000 runs

---

contracts/lib/JurorsTreeSortition.sol
test/lib/jurors-tree-sortition.js
test/registry/jurors-registry-drafting.js

There's no real need for interval zero check, but if it was, the
search wouldn't make any sense.
To choose between this one, #188 or #189.

Jurors Tree: fix interval zero check

---

contracts/controller/Controlled.sol
contracts/controller/Controller.sol
contracts/controller/clock/CourtClock.sol
contracts/controller/config/CourtConfig.sol
contracts/controller/config/CourtConfigData.sol
contracts/controller/config/IConfig.sol
contracts/court/Court.sol
contracts/registry/IJurorsRegistry.sol
contracts/registry/JurorsRegistry.sol
contracts/test/controller/ControllerMock.sol
contracts/test/registry/JurorsRegistryMock.sol
test/controller/controller-config.js
test/court/court-gas.js
test/helpers/controller.js
test/helpers/court.js
test/registry/jurors-registry-activation.js
test/registry/jurors-registry-assign-tokens.js
test/registry/jurors-registry-drafting.js
test/registry/jurors-registry-initialization.js
test/registry/jurors-registry-setters.js
test/registry/jurors-registry-slashing.js
test/registry/jurors-registry-staking.js
test/subscriptions/subscriptions-jurors.js

Court: move minActiveBalance from JurorsRegistry to Config

---

contracts/court/Court.sol
contracts/test/court/CourtMockForVoting.sol
contracts/voting/CRVoting.sol
contracts/voting/ICRVotingOwner.sol
test/court/court-voting.js
test/voting/crvoting-commit.js

Following up #https://github.com/aragon/aragon-court/pull/173

Court: Improve voting methods

---

contracts/controller/Controlled.sol
contracts/controller/Controller.sol
contracts/controller/config/CourtConfig.sol
contracts/controller/config/CourtConfigData.sol
contracts/controller/config/IConfig.sol
contracts/court/Court.sol
contracts/registry/JurorsRegistry.sol
contracts/test/controller/ControllerMock.sol
test/controller/controller-clock.js
test/court/court-gas.js

Config: Optimize min active balance getter

---

contracts/controller/Controller.sol
contracts/standards/ERC900.sol
docs/6-external-interface/1-controller.md
docs/6-external-interface/2-court.md
docs/6-external-interface/3-jurors-registry.md
docs/6-external-interface/4-voting.md
docs/6-external-interface/5-subscriptions.md
docs/6-external-interface/6-treasury.md
docs/6-external-interface/readme.md
docs/7-additional-documentation/readme.md
docs/readme.md

Documenting external getters and events

Docs: Add external interface section

---

contracts/court/Court.sol
docs/4-entry-points/1-controller.md

Docs: Remove heartbeat fees inline comments

---

contracts/arbitration/Arbitrable.sol
contracts/arbitration/IArbitrable.sol
contracts/test/arbitration/ArbitrableMock.sol
test/arbitration/arbitrable.js
test/court/court-gas.js

Arbitrable: Fix ERC165 compliance interface

---

contracts/registry/JurorsRegistry.sol
docs/4-entry-points/4-jurors-registry.md
test/registry/jurors-registry-activation.js

Registry: process deactivation on staking

---

contracts/registry/JurorsRegistry.sol

Registry: remove _draft internal function
Related to #230

Audit: Code recommendations

---

docs/2-architecture/readme.md

Docs: Add governor structure details

---

docs/3-cryptoeconomic-considerations/readme.md
docs/3-trust-assumptions/readme.md
docs/readme.md

Docs: Crypto-economic considerations

---

contracts/disputes/DisputeManager.sol
contracts/registry/JurorsRegistry.sol
docs/6-external-interface/3-dispute-manager.md
docs/6-external-interface/4-jurors-registry.md
test/court/court-gas.js
test/disputes/disputes-draft.js
test/helpers/utils/events.js
test/helpers/wrappers/court.js
test/registry/jurors-registry-activation.js
test/registry/jurors-registry-assign-tokens.js
test/registry/jurors-registry-drafting.js
test/registry/jurors-registry-slashing.js
test/registry/jurors-registry-staking.js
truffle-config.js

After working on the court subgraph I noticed there are some events we are triggering that are a bit loose and some others that we simply forgot to include certain data 🤷‍♂ 
I needed to adjust the `DisputesManager` and the `JurorsRegistry` only, I recommend reviewing by commit tho.

Contracts: Improve emitted events

---

contracts/registry/JurorsRegistry.sol
docs/4-entry-points/4-jurors-registry.md
docs/6-external-interface/4-jurors-registry.md
test/registry/jurors-registry-activation.js
test/registry/jurors-registry-staking.js

Registry: Allow jurors receiving third parties activations

---

contracts/voting/CRVoting.sol
docs/4-entry-points/5-voting.md
docs/6-external-interface/5-voting.md
test/court/court-gas.js
test/disputes/disputes-voting.js
test/helpers/wrappers/court.js
test/voting/crvoting-integration.js
test/voting/crvoting-reveal.js

Voting: Allow revealing votes on behalf of others

---

contracts/court/AragonCourt.sol

Contracts: Remove unused imports

---

readme.md

- Update link target to the Aragon Court [Discord channel](https://discordapp.com/channels/672466989217873929/674689908824342531).

Docs: Update Aragon Chat link

---

readme.md

- Update Discord link, old link was broken for new users

Docs: update chat link

---

package.json

Chore: Ignore test and docs related files from NPM

---

contracts/subscriptions/CourtSubscriptions.sol
test/subscriptions/subscriptions-payments.js
test/subscriptions/subscriptions-setters.js

Subscriptions: Fix transfer to governor
